### ISSUE TITLE
Repair operator

### ISSUE THREAD

**Issue by repressly** [ahmedfgad/GeneticAlgorithmPython#114]
Hello,

I have been playing around with PyGAD within a simulation framework, where I'm doing an optimization of a dynamic problem. The results of that have been not quite satisfactory.

To improve GA results, in general one can turn to a repair operator. Herein lies the problem. I am sorry if I have missed something in the documentation, but it seems like there is no repair operator functionality in PyGAD. It seems to be important if one gets stuck in the realm of not really optimal solutions, since in case GA crossover or mutation operator fail to produce a good enough solution, the repair operator can come in and help fix it, without having to discard a bad solution.

What can I do about it?

**Comment by repressly** [comment]
Hello again,

I have found the way to do the repair. Basically the two functions on_crossover and on_mutation can be customized. I put the code for my repair operator in one of them and call it before the next iteration begins.

**Comment by ahmedfgad** [comment]
Sorry for not responding quickly to your issue.
You can also disable mutation (`mutation_type=None`) and crossover (`crossover_type=None`) and implement your customized crossover and mutation operators in the `on_parents()` callback function.
![](https://user-images.githubusercontent.com/16560492/89446279-9c6f8380-d754-11ea-83fd-a60ea2f53b85.jpg)
