### ISSUE TITLE
keras.ga - How to disable epoch printing?

### ISSUE THREAD

**Issue by Xascoria** [ahmedfgad/GeneticAlgorithmPython#115]
Hello,

I'm trying to use Pygad to train a Keras NN, however, when running `ga_instance.run()`, it always prints these lines every epoch:

```
1/1 [==============================] - 0s 34ms/step
1/1 [==============================] - 0s 36ms/step
1/1 [==============================] - 0s 34ms/step
1/1 [==============================] - 0s 36ms/step
1/1 [==============================] - 0s 31ms/step
1/1 [==============================] - 0s 29ms/step
```
I've looked around but couldn't find a way to disable them, I already have `suppress_warnings=True` when creating the GA

`ga_instance = pygad.GA(num_generations=15, num_parents_mating=5, fitness_func=fitness_func, 
initial_population=keras_ga.population_weights, on_generation=on_generation, suppress_warnings=True, keep_parents=0)`

Thank you for your time.

**Comment by Xascoria** [comment]
Nvm, figured it out, it was because of `model.predict()`

**Comment by ahmedfgad** [comment]
Awesome. Happy your issue is solved!
