### ISSUE TITLE
Links swapped in README.md

### ISSUE THREAD

**Issue by Diamondtroller** [ahmedfgad/GeneticAlgorithmPython#118]
Hello, Ahmed Gad!
Thank you for your awesome library and almost as awesome and useful README.
I wanted to point a minor mistake in [Tutorial: Implementing Genetic Algorithm in Python](https://github.com/ahmedfgad/GeneticAlgorithmPython#tutorial-introduction-to-genetic-algorithm)
`Towards Data Science` links to https://www.kdnuggets.com/2018/03/introduction-optimization-with-genetic-algorithm.html, and
`KDnuggets` links to https://towardsdatascience.com/introduction-to-optimization-with-genetic-algorithm-2f5001d9964b

**Comment by ahmedfgad** [comment]
Hello @Diamondtroller,

Thanks for pointing out to this mistake. It is solved now.
