### ISSUE TITLE
Execute on_crossover callback even if crossover_type is None

### ISSUE THREAD

**Issue by borisarloff** [ahmedfgad/GeneticAlgorithmPython#138]
Currently, the code does not call self.on_crossover(self, self.last_generation_offspring_crossover) on line 1373 when self.crossover_type is None. A callback before executing the mutation segment would be however useful for customizing the mutation type and probability on an offspring-by-offspring basis, even when no crossover is required.

I am requesting that the on_crossover provisioned method be called with a modified or unmodified offspring, regardless to crossover type value. A similar logic would also apply to on_mutation specified callback function.

IMO: In general, any specified callbacks should be exercised throughout the framework pipeline when provisioned, regardless of internal processing. The user should be able to rely on the callbacks being triggered, and then perhaps ignore them as applicable.

Please see additional information added on 10/20/2022, below.

**Comment by borisarloff** [comment]
[code.zip](https://github.com/ahmedfgad/GeneticAlgorithmPython/files/9832002/code.zip)
I have attached a zip file containing a monkey-patch modified pygad v2.18.1 code (pygad_2_18_1_barloff.py) and excerpts of my code (gaengine_excerpt.py).

The modifications to pygad are annotated as "#barloff" for easy search. This modifications (1) allow to pass the user's Class instance reference for persistence flow of computations; (2) this Class instance reference is now declared in the on_<function> GA call implementations, set to None as default at the user side, and (3) specifically for on_crossover and on_mutation references now are always executed, even when crossover_type and mutation_type are None.

The gaengine_excerpt.py module exemplifies the usefulness of these proposed changes. Highlights are annotated by PyDoc comments as "NOTE:" in each case. The onParent(), onFitness(), and onCrossover() static methods are provisioned to on_parent, on_fitness, and on_crossover parameters of GA class constructor. A new "cls_inst" parameter is used to pass on the "self" reference.

The advantage is that a user is able to interact with the GA process from within its own Class instance implementation. The extra parameter cls_inst needed by the on_<referenced> callbacks can be ignored, if not needed.

In the gaengine_excerpt.py implementation, one assumption is made that the fitness list sequentially corresponds to the offspring returned by on_crossover. Please advice if that is not the case, a code review seems to indicate that it is the case.

Request that the proposed changes be adopted in a future  release of pygad.py module.

**Comment by borisarloff** [comment]
Pull request #143 was submitted and it is pending addressing this issue by @borisarloff.

**Comment by ahmedfgad** [comment]
@borisarloff,

This feature is supported in PyGAD 2.18.2:
* The on_crossover() and on_mutation() callback functions/methods are called even if `crossover_type=None` or `mutation_type=None`.

The new release will support:
* Passing class methods as the fitness and callbacks. The first argument in these methods is a reference to the calling class instance.

Thanks for your suggestions.
