### ISSUE TITLE
Bug in indexing. Code fails with error. 

### ISSUE THREAD

**Issue by why-not** [ahmedfgad/GeneticAlgorithmPython#147]
https://github.com/ahmedfgad/GeneticAlgorithmPython/blob/251072766d8a9f3ea03ab41f74cda2e8c20c21d0/example_custom_operators.py#L58

Easy fix. 
It Should be 
```        random_gene_idx = numpy.random.choice(range(offspring.shape[1]))```

**Comment by ahmedfgad** [comment]
Thanks @why-not. It is now solved.
