### ISSUE TITLE
keras.ga - How can I disable printing for every step?

### ISSUE THREAD

**Issue by vader-coder** [ahmedfgad/GeneticAlgorithmPython#148]
I am using the kerasga module and it keeps printing for every step like so:

```
1/1 [==============================] - 0s 7ms/step
1/1 [==============================] - 0s 8ms/step
1/1 [==============================] - 0s 7ms/step
```

All the google answers that I can find tell me to put `verbose=0` when I call keras' `model.predict`. 
However, I am not calling model.predict, I am calling `pygad.kerasga.predict(model=model,
                                         solution=solution,
                                         data=state)`
and this function doesn't support a verbose flag. What can I do to stop it from printing on every step?
My pygad version is `2.18.1` and my python version is `3.10.6`.

**Comment by BenoitMiquey** [comment]
Hi, i had the same problem, 

to fix this, edit the kerasga.py file, line 44 add this :
`predictions = model.predict(data, **verbose="0"**)`
