### ISSUE TITLE
Bug module 'numpy' has no attribute 'int'. Did you mean: 'inf'?

### ISSUE THREAD

**Issue by JavaProgswing** [ahmedfgad/GeneticAlgorithmPython#151]
Traceback (most recent call last):
  File "C:\Users\HP\Desktop\Programs\Python\Testing\test.py", line 1, in <module>
    import pygad
  File "C:\Users\HP\.virtualenvs\Testing-x9UQs_eI\lib\site-packages\pygad\__init__.py", line 1, in <module>
    from .pygad import * # Relative import.
  File "C:\Users\HP\.virtualenvs\Testing-x9UQs_eI\lib\site-packages\pygad\pygad.py", line 9, in <module>
    class GA:
  File "C:\Users\HP\.virtualenvs\Testing-x9UQs_eI\lib\site-packages\pygad\pygad.py", line 11, in GA
    supported_int_types = [int, numpy.int, numpy.int8, numpy.int16, numpy.int32, numpy.int64, numpy.uint, numpy.uint8, numpy.uint16, numpy.uint32, numpy.uint64]
  File "C:\Users\HP\.virtualenvs\Testing-x9UQs_eI\lib\site-packages\numpy\__init__.py", line 284, in __getattr__
    raise AttributeError("module {!r} has no attribute "
AttributeError: module 'numpy' has no attribute 'int'. Did you mean: 'inf'?

**Comment by BenoitMiquey** [comment]
Hi, 

Can you give the steps to reproduce this bug ?

**Comment by JavaProgswing** [comment]
I actually tried a sample code in a pipenv and it gave me this error.

`
import pygad

# Define the function to be optimized


def fitness_func(x):
    return x**2


# Set the number of variables (in this case, x) and the number of generations
num_variables = 1
num_generations = 100

# Set the lower and upper bounds for x
lower_bound = [0]
upper_bound = [10]

# Set the crossover and mutation rate
crossover_rate = 0.8
mutation_rate = 0.2

# Create the PyGAD object
ga = pygad.GeneticAlgorithm(num_variables=num_variables,
                            num_generations=num_generations,
                            lower_bound=lower_bound,
                            upper_bound=upper_bound,
                            crossover_rate=crossover_rate,
                            mutation_rate=mutation_rate,
                            fitness_func=fitness_func)

# Run the optimization
best_solution = ga.run()

# Print the best solution
print(best_solution)
`

**Comment by julianbieber** [comment]
I think I had the same issue.
From what I understand, numpy 1.24.0 was released 3 days ago, and they removed some deprecated aliases, one of which is numpy.int.

https://github.com/numpy/numpy/releases/tag/v1.24.0:
```
The deprecation for the aliases np.object, np.bool, np.float,
np.complex, np.str, and np.int is expired (introduces NumPy
1.20). Some of these will now give a FutureWarning in addition to
raising an error since they will be mapped to the NumPy scalars in
the future.
```

By using a previous version of numpy I was able to work around the issue.
```
python3 -m pip install numpy==1.23.5
```

**Comment by EgorBlagov** [comment]
Here is the PR fixing the issue: https://github.com/ahmedfgad/GeneticAlgorithmPython/pull/152

**Comment by connorfuhrman** [comment]
Had a similar issue and had to revert to `numpy<=1.20`. I then had troubles installing that version of numpy with Python > 3.9.

**Comment by uid89626** [comment]
Happened to me too on python 3.10.5 with numpy 1.24.1.
numpy.int and numpy.float seem removed. fix is to update pygad.py like
`class GA:

    supported_int_types = [int, numpy.int8, numpy.int16, numpy.int32, numpy.int64, numpy.uint, numpy.uint8, numpy.uint16, numpy.uint32, numpy.uint64]
    supported_float_types = [float, numpy.float16, numpy.float32, numpy.float64]
`

**Comment by johnosbb** [comment]
Same issue, using the reference code provided on the main page:

    raise AttributeError("module {!r} has no attribute "
AttributeError: module 'numpy' has no attribute 'int'. Did you mean: 'inf'?
