### ISSUE TITLE
Optimize problem using constraints

### ISSUE THREAD

**Issue by deathlyhallows010** [ahmedfgad/GeneticAlgorithmPython#19]
Hi @ahmedfgad 

Let's consider     
y = f(w1:w6) = w1x1 + w2x2 + w3x3 + w4x4 + w5x5 + 6wx6
where (x1,x2,x3,x4,x5,x6)=(4,-2,3.5,5,-11,-4.7) and y=44

Is it possible to get the best solution for constrained weight parameter i.e if I want w1 to vary from (0,1) and w2 from (10,100) and so on ..... (Different bounds for each variable)

Thanks

**Comment by keithreid-sfw** [comment]
Hello. I am not Dr Gad but I have an answer for you which you can take or leave. 

Please note that you have asked your question in the abstract without code and so I am answering in the same style. If you present a minimum reproducible example, a small snippet of code, then I would answer in kind.  

I interpret your question as ‘in addition to the mutation, recombination and other genetic stuff, is it possible to ensure that a given gene is within numerical limits’. 

Yes this is possible.

To answer in the abstract, you can look at your answer, compare it to the limits and then change it if your answer breaches the limits.  The efficient implementation of this is open to discussion.  Two approaches come to mind. 

If you want the last value to be ```0.5 < gene < 1.0```

If you find that you get an algo:

```a = [0.1, 0.2, 0.3, 0.01, 0.03, 42]```

You can refer to the last one as 

```algo[5]``` 

as you may know.  Then you can do an if; elif; else; operation on it.  For example changing values below 0.5 to 0.5.  

A second approach, which you can also do, is to start your initial population with values near your desired values and have small mutation rates or a short run time.  

The implementation is up to you unless you present code. I hope this helps  and that you continue to enjoy Dr Gad’s excellent repo.

**Comment by ahmedfgad** [comment]
Hi @deathlyhallows010 ,

PyGAD supports a parameter called `gene_space` which allows you to specify the range or space of values for each gene.

Here is an example where the range of the first is 0:1, the range is 10:100 for the second gene, and so on:
```python
gene_space=[range(0, 1), range(10, 100), range(4, 20), range(-10, 25), range(100, 200), range(-4, 4)]
```

In case that a gene is assigned a discrete set of values, then you can also specify these values as a list. Here is an example where there are just 2 genes. The possible values for the first gene are `[1, 18, 44, 65]`. For the second gene, the values are `[-4, 6, 121, 40, 25]`.
```python
gene_space=[[1, 18, 44, 65], [-4, 6, 121, 40, 25]]
```

I hope that helps.

Thanks @keithreid-sfw for your answer :)

Regards,
Ahmed

**Comment by ahmedfgad** [comment]
Here is a complete example that uses the `gene_space` parameter in the `pygad.GA` class:

```python
import pygad
import numpy

function_inputs = [4,-2,3.5,5,-11,-4.7] # Function inputs.
desired_output = 44 # Function output.

def fitness_func(solution, solution_idx):
    output = numpy.sum(solution*function_inputs)
    fitness = 1.0 / numpy.abs(output - desired_output)
    return fitness

fitness_function = fitness_func

num_generations = 100 # Number of generations.
num_parents_mating = 7 # Number of solutions to be selected as parents in the mating pool.

sol_per_pop = 50 # Number of solutions in the population.
num_genes = len(function_inputs)

keep_parents = 7 # Number of parents to keep in the next population. -1 means keep all parents and 0 means keep nothing.

mutation_percent_genes = 10 # Percentage of genes to mutate. This parameter has no action if the parameter mutation_num_genes exists or when mutation_type is None.

last_fitness = 0
def callback_generation(ga_instance):
    global last_fitness
    print("Generation = {generation}".format(generation=ga_instance.generations_completed))
    print("Fitness    = {fitness}".format(fitness=ga_instance.best_solution()[1]))
    print("Change     = {change}".format(change=ga_instance.best_solution()[1] - last_fitness))
    last_fitness = ga_instance.best_solution()[1]

ga_instance = pygad.GA(num_generations=num_generations,
                       num_parents_mating=num_parents_mating, 
                       fitness_func=fitness_function,
                       sol_per_pop=sol_per_pop, 
                       num_genes=num_genes,
                       keep_parents=keep_parents,
                       mutation_percent_genes=mutation_percent_genes,
                       callback_generation=callback_generation,
                       gene_space=[range(0, 1), range(10, 100), range(4, 20), range(-10, 25), range(100, 200), range(-4, 4)])

ga_instance.run()

ga_instance.plot_result()

solution, solution_fitness, solution_idx = ga_instance.best_solution()
print("Parameters of the best solution : {solution}".format(solution=solution))
print("Fitness value of the best solution = {solution_fitness}".format(solution_fitness=solution_fitness))
print("Index of the best solution : {solution_idx}".format(solution_idx=solution_idx))

prediction = numpy.sum(numpy.array(function_inputs)*solution)
print("Predicted output based on the best solution : {prediction}".format(prediction=prediction))
```

**Comment by deathlyhallows010** [comment]
Hi @ahmedfgad 
Thank you very much. That's exactly what I was looking for. 
Appreciated 👍.
