### ISSUE TITLE
Bug in save best solutions

### ISSUE THREAD

**Issue by screetech** [ahmedfgad/GeneticAlgorithmPython#25]
## Description

If `save_best_solutions = True`, the `best_solutions` list is overwritten after each generation when a new population is being generated. A bug appears on line number 748.  Solutions stored in `best_solutions` are probably just shallow copies, i.e., pointers to `population`.

## What the bug looks like

`best_solutions = []`
`best_solutions = [[9, 10, 5, 9, 9]]` # after append on the line 728, it holds first best solution found
`best_solutions = [[6, 9, 6, 9, 6]]` # after the line 748, original value has been changed (changed after every single generation)

**Comment by ahmedfgad** [comment]
Thanks.

The bug is fixed by creating a copy of the best solution. This prevents a solution saved in the `best_solutions` attribute from being changed.

The next line:
```python
best_solution = self.population[best_match_idx, :]
```

is replaced by this line:
```python
best_solution = self.population[best_match_idx, :].copy()
```

**Comment by ahmedfgad** [comment]
PyGAD 2.10.2 is released which addresses this issue. Thank you :)
