### ISSUE TITLE
KerasGA error: AttributeError: module 'pygad.kerasga' has no attribute 'KerasGA'

### ISSUE THREAD

**Issue by cric96** [ahmedfgad/GeneticAlgorithmPython#51]
Hi! 
I have tried to run the example that combines keras with your library ([that one](https://github.com/ahmedfgad/KerasGA/blob/master/keras_pygad_XOR_classification.py)).

But python can't find the class KerasGA (as showed in the title)

I installed pygad using pip `pip install pygad`.

Looking in the file __init__.py I tried to  add:
```
from .kerasga import * # Relative import.
```

And it seems to solve the problem...

**Comment by ahmedfgad** [comment]
Hi,

Thank you.

I am sorry that I have missed that for TorchGA and KerasGA. It is solved and PyGAD 2.15.2 is released.

Please upgrade to the latest version:

```python
pip install --upgrade pygad
```
