### ISSUE TITLE
Project doesn't state a license

### ISSUE THREAD

**Issue by kittentronic** [ahmedfgad/GeneticAlgorithmPython#59]
The README.md describes this project as 'open-source' but I can't find an actual license anywhere.
Please choose and specify the license under which this code is released as open-source, so that potential users and contributors know what they are permitted to do with it and under what conditions.

**Comment by Vlasius** [comment]
(XXXX) C:\Users\XXX\Desktop\XXX\XXX>pip show pygad
Name: pygad
Version: 2.16.0
Summary: PyGAD: A Python 3 Library for Building the Genetic Algorithm and Training Machine Learning Algoithms (Keras & PyTorch).
Home-page: https://github.com/ahmedfgad/GeneticAlgorithmPython
Author: AhXXX XXXX XXXX
Author-email: ahXXXXXXX@gmail.com
License: UNKNOWN
Location: c:\users\XXX\desktop\XXXX\XXXX\XXX\site-packages
Requires: matplotlib, numpy
Required-by:

you can check by yourself in the terminal. It's not defined. 
As long you are using the version with unknown licence, the conditions are defined by the main contributor AFAIK.

**Comment by hyandell** [comment]
Seconding this; there's no license provided for this software.

**Comment by CompRhys** [comment]
@ahmedfgad Can you please update this project to include a license?

**Comment by hyandell** [comment]
As the project currently has activity, updating to flag this concern to make it more visible.
