### ISSUE TITLE
Customize initialize_population()

### ISSUE THREAD

**Issue by yoonghm** [ahmedfgad/GeneticAlgorithmPython#6]
The `initialize_population()` is called directly by the constructor of GA, i.e., `__init__()`.
That function randomly creates values from -4 to 4.  I have a feeling that that function should be customized, just like `fitness_func()` so that it could be adapted based on problems at hand.

**Comment by ahmedfgad** [comment]
Hello @yoonghm ,

This is a good suggestion to be added in the project and reflected in the [PyGAD library](https://pypi.org/project/pygad). I will take care of customizing the initial population to allow the user to specify the range from which the gene values will be selected.

**Comment by ahmedfgad** [comment]
Hello @yoonghm ,
Both the [GitHub project](https://github.com/ahmedfgad/GeneticAlgorithmPython) and the [PyPI library (PyGAD)](https://pypi.org/project/pygad) are updated to customize the initial population using 2 parameters:
1. init_range_low
2. init_range_high

For more information, you can check the documentation at GitHub (https://github.com/ahmedfgad/GeneticAlgorithmPython) and PyPI (https://pypi.org/project/pygad).

Thanks for your suggestion and I am excited to hear more from you :)
