### ISSUE TITLE
Use of custom `parent_selection_type` function

### ISSUE THREAD

**Issue by SiggyF** [ahmedfgad/GeneticAlgorithmPython#60]
Hi,

Thanks for  your great module. I have an implementation question that might be an issue.  I am trying to use a custom fitness function with multiple variables. I also implemented a custom `parent_selection_type` which uses a custom function to sort the multivariate fitness function. I then run into an issue that, regardless of the `parent_selection_type` function that I passed the `self.steady_state_selection` function is called in [run](https://github.com/ahmedfgad/GeneticAlgorithmPython/blob/c87641bb9f774cebc40a45e70834832b04ae32b5/pygad.py#L1247) function. 

Could it be that it would be more logical to call the custom `parent_selection_type` here, which is available as `self.select_parents`?

Thanks for taking this into consideration. 

Kind regards,

Fedor Baart

**Comment by ahmedfgad** [comment]
Hi Fedor,

Thanks for using PyGAD!

The feature of using a custom parent selection function is already supported. Just assign your custom function to the `parent_selection_type` parameter. Please [check the documentation](https://pygad.readthedocs.io/en/latest/README_pygad_ReadTheDocs.html#user-defined-crossover-mutation-and-parent-selection-operators) for details about the expected signature of the user-defined function: https://pygad.readthedocs.io/en/latest/README_pygad_ReadTheDocs.html#user-defined-crossover-mutation-and-parent-selection-operators

Please have a try and let me know if you have any issues using your custom parent selection function.

Regards,
Ahmed

**Comment by SiggyF** [comment]
Thanks for your explanation
