### ISSUE TITLE
Add plot customization feature

### ISSUE THREAD

**Issue by QiotoF** [ahmedfgad/GeneticAlgorithmPython#9]
Hello!

I want to ask for a plot customization feature, so one can title plots, or make subplots for example. Now all plot_result() method does is plotting a result and one can't do anything more with it.

Thank you!

**Comment by ahmedfgad** [comment]
Hello,

Thanks for your suggestion.

The `plot_result()` function is updated and it supports 3 optional parameters:
1. title: Figure title.
2. xlabel: X-axis label.
3. ylabel: Y-axis label.

Could you clarify what subplots to make?

Regards,
Ahmed

**Comment by ahmedfgad** [comment]
Closed for no further interaction.
